name: Build Wino Mail

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: Target branch to build from
        default: dev
        type: string
  workflow_call:
    inputs:
      target_branch:
        description: Target branch to build from
        default: dev
        type: string

jobs:
  build:
    name: Build app
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64, arm64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ inputs.target_branch }}

      - name: Import certificate
        run: |
          $CertificatePath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "Certificate.pfx"
          [IO.File]::WriteAllBytes($CertificatePath, [Convert]::FromBase64String("${{ secrets.CERTIFICATE_FILE }}"))

          $password = ConvertTo-SecureString -String "${{ secrets.CERTIFICATE_PASSWORD }}" -Force -AsPlainText
          Import-PfxCertificate -FilePath $CertificatePath -CertStoreLocation Cert:/CurrentUser/My -Password $password

          Remove-Item -Path $CertificatePath -Force

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57

      - name: Restore solution
        run: |
          $arguments = @(
              '/p:Configuration=Release',
              '/p:Platform=${{ matrix.platform }}',
              '-verbosity:minimal'
          )
          msbuild WinoMail.slnx /t:Restore @arguments

      - name: Build solution
        run: |
          $arguments = @(
              '/p:Configuration=Release',
              '/p:Platform=${{ matrix.platform }}',
              '/p:AppxBundlePlatforms=${{ matrix.platform }}',
              '/p:UapAppxPackageBuildMode=SideloadOnly',
              '/p:AppxPackageSigningEnabled=True',
              '/p:GenerateTemporaryStoreCertificate=False',
              '/p:PackageCertificateThumbprint=${{ secrets.CERTIFICATE_THUMBPRINT }}',
              '/p:AppxBundleNameForOutput=Wino-Mail-${{ matrix.platform }}',
              '-verbosity:minimal'
          )
          msbuild WinoMail.slnx @arguments

      - name: Upload build artifacts
        uses: actions/upload-artifact@c6a366c94c3e0affe28c06c8df20a878f24da3cf
        with:
          name: Wino-Mail-${{ matrix.platform }}-${{ github.sha }}
          path: |
            WinoMail.Packaging/AppPackages/**/Wino-Mail-${{ matrix.platform }}.msixbundle
            WinoMail.Packaging/AppPackages/**/Dependencies/${{ matrix.platform }}/**/*
